### PR TITLE
Clean up Lovense message initliaization

### PR DESCRIPTION
**Pull request by hiss-remi**
Per #439.

### CODE REVIEW

**Comment by hiss-remi** [comment]
Upon further investigation, this changes behavior for unknown devices - they won't get any functionality at all. Will fix soon.

**Comment by qdot** [comment]
Hah, was just looking at that myself, especially since CI didn't seem to send the test failure back to github.

Looks like you can just turn line 158 from a return of an error, to a "log error message and keep going" and I think that might do it?

**Comment by hiss-remi** [comment]
I'm not sure that'd work without stuffing more of the following logic into else blocks. I'm pretty sure the name assignment would cause some errors if nothing else.

I was thinking put the common messages into a function, then call it before returning where appropriate. It feels a bit inelegant, but I think it'd be more readable.

**Comment by qdot** [comment]
Sure, that'll work. Lovense hasn't really been cranking out the new hardware lately anyways, so if something new does come out, we can deal with it then.

**Comment by hiss-remi** [comment]
I went ahead and implemented it like that, then commented out a device type to test the behavior. And it looks like when Initialize returns Error, it doesn't get added to the device list (which makes sense in retrospect), making the thing with the messages academic. Whoops.

To be consistent with sorta-recognize-them device handling and make it do what the comments sound like it's supposed to do, I think we'd need to just log the error message and then return Ok. Although it only specifically mentions the "treat as a single vibrator" for the unrecognized device type error. Getting a deviceInfoString that doesn't match the pattern is out there enough that maybe in that case it's better to just leave the thing alone.

I've made a commit that does what the comments suggest it should.

**Comment by qdot** [comment]
Ugh. I really wish github was better about notifying me about updates.

Sorry about dropping this for the past month. I'll try to get this in this weekend. Note that it may require me rebasing it myself since master has changed, but it'll still have your author name on it.

**Comment by qdot** [comment]
Coming in as part of #457. I cherry-picked the patch and just had to change a couple of type names that changed during the megapatch. :)

**Pull request closed without merging**
