### PR TITLE
Small schema fix for LinearCmd

### PR DESCRIPTION
**Pull request by Tvde1**

### CODE REVIEW

**Comment by Tvde1** [comment]
@blackspherefollower did that. If that solves the issue this PR can also be closed.

**Comment by blackspherefollower** [comment]
@Tvde1 Nice.
Just to be clear, I have no power here; however, I'll advise where I can so that all the ducks are lined up for when @qdot gets online.

**Comment by qdot** [comment]
The PR doesn't need to be in the schema repo. The schema repo exists here as a subtree merge, so I could just do a subtree push from here to there if need be. That's why it's subtree'd, so if we find something broken in a project, we can fix it there and not require the user to fix in the schema repo also.

**Comment by qdot** [comment]
Brought this in on the new dev branch. Closing.

**Pull request closed without merging**
